server:
  port: 8081
  servlet:
    context-path: /stategrid

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9jl1hu574zl788iwo.mysql.rds.aliyuncs.com:3306/cdwd?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: suep
    password: Suepsuep1

